### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by gongxxuan** [chaimi2013/3R#1]
您好，我想问一下您的数据集什么时候公开？

**Comment by chaimi2013** [comment]
> 您好，我想问一下您的数据集什么时候公开？

I will prepare the datasets ASAP. I guess they can be released before the end of October.

**Comment by ywj95** [comment]
期待作者公开数据集

**Comment by chaimi2013** [comment]
> 期待作者公开数据集

The datasets and code of 3R have been released.
