### ISSUE TITLE
Please how to change the light positions and colors in the NHC dataset?

### ISSUE THREAD

**Issue by dreamsPower** [chaimi2013/3R#10]
Dear Dr. Zhang,
Hi!
The 3R approach points out "We synthesized 5 images for each of them by changing the light positions and colors, resulting in a total of 2,750 images, called “Nighttime Hazy Cityscapes” (NHC). "

Please how to adjust light positions and light colors to generate 5 nighttime hazy images for each of them? In your code, two parameters "xInterval" and "imgLowLightColor"  correspond to the light positions and colors, respectively. What is their range of values? 

Thank you for your help. Hope to receive your reply soon!

**Comment by chaimi2013** [comment]
> Dear Dr. Zhang, Hi! The 3R approach points out "We synthesized 5 images for each of them by changing the light positions and colors, resulting in a total of 2,750 images, called “Nighttime Hazy Cityscapes” (NHC). "
> 
> Please how to adjust light positions and light colors to generate 5 nighttime hazy images for each of them? In your code, two parameters "xInterval" and "imgLowLightColor" correspond to the light positions and colors, respectively. What is their range of values?
> 
> Thank you for your help. Hope to receive your reply soon!

I have just provided the download link for the NRC datasets. Please have a try. Or you can use the provided config and related dataset to generate the dataset.
