### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by HIGHGUI** [chaimi2013/3R#3]
Thank to release the datasets.

It is nice work!

However,  there seems to be no pictures in the NHC dataset. 

Please check.

Thank you.

**Comment by chaimi2013** [comment]
> Thank to release the datasets.
> 
> It is nice work!
> 
> However, there seems to be no pictures in the NHC dataset.
> 
> Please check.
> 
> Thank you.

Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.

**Comment by HIGHGUI** [comment]
> > Thank to release the datasets.
> > It is nice work!
> > However, there seems to be no pictures in the NHC dataset.
> > Please check.
> > Thank you.
> 
> Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.

Thank you for your reply.

I will try to make NHC.

Thank you.

**Comment by gongxxuan** [comment]
> > Thank to release the datasets.
> > It is nice work!
> > However, there seems to be no pictures in the NHC dataset.
> > Please check.
> > Thank you.
> 
> Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.



> > > Thank to release the datasets.
> > > It is nice work!
> > > However, there seems to be no pictures in the NHC dataset.
> > > Please check.
> > > Thank you.
> > 
> > 
> > Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.
> 
> Thank you for your reply.
> 
> I will try to make NHC.
> 
> Thank you.
Have you successfully synthesized NHC dataset? After synthesizing an image, the code reports an error below;and the synthesized  image is also incorrect.
![image](https://user-images.githubusercontent.com/67060808/100178326-a0dfc800-2f0e-11eb-839d-53991d378401.png)

**Comment by chaimi2013** [comment]
> > > Thank to release the datasets.
> > > It is nice work!
> > > However, there seems to be no pictures in the NHC dataset.
> > > Please check.
> > > Thank you.
> > 
> > 
> > Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.
> 
> > > > Thank to release the datasets.
> > > > It is nice work!
> > > > However, there seems to be no pictures in the NHC dataset.
> > > > Please check.
> > > > Thank you.
> > > 
> > > 
> > > Yes. There are only placeholders in the folder of HNC. Due to the license of the Cityscapes dataset, I cannot release the processed dataset. You can download the Cityscapes dataset by yourself, put it in the corresponding folder, and run the code. Then you will get NHC. Good luck.
> > 
> > 
> > Thank you for your reply.
> > I will try to make NHC.
> > Thank you.
> > Have you successfully synthesized NHC dataset? After synthesizing an image, the code reports an error below;and the synthesized  image is also incorrect.

It seems that the depth map is incorrect. It should be pre-processed first. Please refer to the code in "code/3R/nightHazeSyn/cityscapes/ultis".

**Comment by gongxxuan** [comment]
我想请问一下在NHC目录下面各个文件夹里面应该对应下载 Cityscapes 数据集中的那些数据集？
![image](https://user-images.githubusercontent.com/67060808/100184563-bd82fc80-2f1c-11eb-8757-ec80785a0294.png)

**Comment by gongxxuan** [comment]
I download the Cityscapes dataset, put it in the corresponding folder, and run the code. But the code reports an error below.
![image](https://user-images.githubusercontent.com/67060808/100690602-d75f8c00-33c1-11eb-90da-9f30adf08237.png)

**Comment by YQ-Yang** [comment]
hello,How can i use my own datasets to generate haze?  Thank you for your reply

**Comment by chaimi2013** [comment]
> hello,How can i use my own datasets to generate haze? Thank you for your reply

Sure. You need depth map, camera pose, semantic label as the Cityscapes dataset. Or you need depth map and synthesize the hazy image as the RESIDE and Middlebury datasets.

**Comment by YQ-Yang** [comment]
> > hello,How can i use my own datasets to generate haze? Thank you for your reply
> 
> Sure. You need depth map, camera pose, semantic label as the Cityscapes dataset. Or you need depth map and synthesize the hazy image as the RESIDE and Middlebury datasets.

Sorry,I mean i don't know the procedure to use your repo to my datasets.If it's convenient,please tell me the details!!!thank you

**Comment by YQ-Yang** [comment]
> > hello,How can i use my own datasets to generate haze? Thank you for your reply
> 
> Sure. You need depth map, camera pose, semantic label as the Cityscapes dataset. Or you need depth map and synthesize the hazy image as the RESIDE and Middlebury datasets.

Sorry,I mean i don't know the procedure to use your repo on my datasets.If it's convenient,please tell me the details!!!thank you

**Comment by chaimi2013** [comment]
> > > hello,How can i use my own datasets to generate haze? Thank you for your reply
> > 
> > 
> > Sure. You need depth map, camera pose, semantic label as the Cityscapes dataset. Or you need depth map and synthesize the hazy image as the RESIDE and Middlebury datasets.
> 
> Sorry,I mean i don't know the procedure to use your repo on my datasets.If it's convenient,please tell me the details!!!thank you

If you have depth map, camera pose, semantic label as the Cityscapes dataset, please follow the logic in **/3R/code/3R/nightHazeSyn/cityscapes** to synthesize the hazy image. Or if you only have depth map as the RESIDE and Middlebury datasets, please follow the logic in **/3R/code/3R/nightHazeSyn/middlebury_RESIDE** synthesize the hazy image.

**Comment by YQ-Yang** [comment]
> > > > hello,How can i use my own datasets to generate haze? Thank you for your reply
> > > 
> > > 
> > > Sure. You need depth map, camera pose, semantic label as the Cityscapes dataset. Or you need depth map and synthesize the hazy image as the RESIDE and Middlebury datasets.
> > 
> > 
> > Sorry,I mean i don't know the procedure to use your repo on my datasets.If it's convenient,please tell me the details!!!thank you
> 
> If you have depth map, camera pose, semantic label as the Cityscapes dataset, please follow the logic in **/3R/code/3R/nightHazeSyn/cityscapes** to synthesize the hazy image. Or if you only have depth map as the RESIDE and Middlebury datasets, please follow the logic in **/3R/code/3R/nightHazeSyn/middlebury_RESIDE** synthesize the hazy image.

Okay,I got it.Thank you very much
