### ISSUE TITLE
SSIM 值

### ISSUE THREAD

**Issue by gongxxuan** [chaimi2013/3R#4]
I want to know how you calculate the SSIM value, why the SSIM value I calculated is different from the result in your paper？

**Comment by chaimi2013** [comment]
> I want to know how you calculate the SSIM value, why the SSIM value I calculated is different from the result in your paper？

it should be "from skimage.metrics import structural_similarity as ssim"

**Comment by gongxxuan** [comment]
> > I want to know how you calculate the SSIM value, why the SSIM value I calculated is different from the result in your paper？
> 
> it should be "from skimage.metrics import structural_similarity as ssim"

How do you set the parameters of the "from skimage.metrics import structural_similarity as ssim" function? Because the value that I calculated with this function differs from what you found in your paper.

**Comment by chaimi2013** [comment]
> > > I want to know how you calculate the SSIM value, why the SSIM value I calculated is different from the result in your paper？
> > 
> > 
> > it should be "from skimage.metrics import structural_similarity as ssim"
> 
> How do you set the parameters of the "from skimage.metrics import structural_similarity as ssim" function? Because the value that I calculated with this function differs from what you found in your paper.

"data_range=1, multichannel=True"

**Comment by gongxxuan** [comment]
> > > > I want to know how you calculate the SSIM value, why the SSIM value I calculated is different from the result in your paper？
> > > 
> > > 
> > > it should be "from skimage.metrics import structural_similarity as ssim"
> > 
> > 
> > How do you set the parameters of the "from skimage.metrics import structural_similarity as ssim" function? Because the value that I calculated with this function differs from what you found in your paper.
> 
> "data_range=1, multichannel=True"
For the same function, some of my results in NHC dataset differ from those in your paper by about 0.07,sometime more.

**Comment by gongxxuan** [comment]
Does the ground truth haze-free image used in the paper when calculating SSIM value refer to the low-light image?

**Comment by chaimi2013** [comment]
> Does the ground truth haze-free image used in the paper when calculating SSIM value refer to the low-light image?

Exactly
