### ISSUE TITLE
code

### ISSUE THREAD

**Issue by chenhuidmu** [chaimi2013/3R#5]
Hello, could you please provide the codes of OSFD and ND-Net, or send them to my email chenhuidmu@163.com. thank you

**Comment by gongxxuan** [comment]
Hello, could you please provide the codes of OSFD and ND-Net, or send them to my email 18438620597@163.com. thank you

**Comment by chaimi2013** [comment]
Thanks for your interest in this work. Due to the tight schedule, I will try to release the code of OSFD after June. Or you can send your test images to me, I will try to process them.

**Comment by chenhuidmu** [comment]
Dear Jing Zhang
I am very glad to receive your email. I need to  use OSFD method to test the effect of 897 nighttime images of val. json in MM2020_3R_DataSets . thank you.
















At 2021-03-30 09:56:08, "chaimi2013" ***@***.***> wrote:

Thanks for your interest in this work. Due to the tight schedule, I will try to release the code of OSFD after June. Or you can send your test images to me, I will try to process them.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
valnightHazy.zip (20.3M, 2021年4月14日 21:02 到期)
下载
