### ISSUE TITLE
ND-Net

### ISSUE THREAD

**Issue by chenhuiphd** [chaimi2013/3R#9]
Hi, Could you please public the code of ND-Net? I want to learn it. Thank you.

**Comment by chenhuiphd** [comment]
Hello, did you use 8073 pairs of NHR images to do ND-Net training, and then use 897 haze images to do network testing to calculate PSNR and SSIM parameter indicators? Currently, there is color bias problem in my haze result, could you please public your ND-Net code, I would like to learn the parameter configuration below, thank you.

**Comment by chaimi2013** [comment]
> Hi, Could you please public the code of ND-Net? I want to learn it. Thank you.

ND-Net is based on a simple encoder-decoder structure, which has been described in the paper. Please refer to the structure details and implement it. By the way, I have provided the download links to NHR and NHC. You can try to train ND-Net on them.
